version: '3'

services:
  server:
    build: .
    command: /app/build/bin/server

  client:
    build: .
    command: sh -c "sleep 5 && /app/build/bin/client & /app/build/bin/other_client"
    depends_on:
      - server